-- 테이블 스키마
insert into table_schema(id, schema_name, user_id, exported_at,created_at,created_by,modified_at,modified_by)
values
    (1,'test_schema','jang',null,now(),'jangwangyu',now(),'jangwangyu')
;

-- 테이블 스키마 id를 직접 입력했으니, auto_increment 수치를 직접 제어해야함
ALTER TABLE table_schema AUTO_INCREMENT=2;

-- 예제 테이블 스키마 필드
insert into schema_field (table_schema_id, field_order, field_name, mock_data_type,
                          type_option_json, blank_percent, force_value,
                          created_at, created_by, modified_at, modified_by)
values
(1,1,'id','ROW_NUMBER','{"start": 1,"step": 1}',0,null,now(),'asd',now(),'asd'),
(1,2,'age','NUMBER','{"min": 1,"max": 30,"decimals": 0}',50, null,now(),'asd',now(),'asd'),
(1,6,'name','STRING','{"minLength": 1, "maxLength": 10}', 0, null,now(),'asd',now(),'asd'),
(1,4,'active','BOOLEAN',null,0,'true',now(),'asd',now(),'asd')
;


-- 샘플 가짜 데이터
insert into mock_data(mock_data_type, mock_data_value)
values
    ('NAME', '김민준'),
    ('NAME', '이서준'),
    ('NAME', '박지민'),
    ('NAME', '최유진'),
    ('NAME', '정우성'),
    ('NAME', '조민수'),
    ('NAME', '강다니엘'),
    ('NAME', '임지현'),
    ('NAME', '윤아'),
    ('NAME', '장하준'),
    ('NAME', '오세훈'),
    ('NAME', '한지민'),
    ('NAME', '서지혜'),
    ('NAME', '배수지'),
    ('NAME', '신동엽'),
    ('NAME', '이정재'),
    ('NAME', '김태희'),
    ('NAME', '이병헌'),
    ('NAME', '전지현'),
    ('NAME', '김소현'),
    ('NAME', '이민호'),
    ('NAME', '박보검'),
    ('NAME', '정해인'),
    ('NAME', '김고은'),
    ('NAME', '이유리'),
    ('NAME', '최강희'),
    ('NAME', '한석규'),
    ('NAME', '이준기'),
    ('NAME', '김희선'),
    ('NAME', '박신혜'),
    ('NAME', '정유미'),
    ('NAME', '이상윤'),
    ('NAME', '김영광'),
    ('NAME', '이하늬'),
    ('NAME', '조정석'),
    ('NAME', '김민희'),
    ('NAME', '이상화'),
    ('NAME', '박서준'),
    ('NAME', '정소민'),
    ('NAME', '한예슬'),
    ('NAME', '이상엽'),
    ('NAME', '김지수'),
    ('NAME', '이재욱'),
    ('NAME', '박하선'),
    ('NAME', '정인선'),
    ('NAME', '이유진'),
    ('NAME', '김상중'),
    ('NAME', '이정은'),
    ('NAME', '박지윤'),
    ('NAME', '정재영'),
    ('NAME', '한지상'),
    ('NAME', '이상민'),
    ('NAME', '김민정'),
    ('NAME', '이재훈'),
    ('NAME', '박소담'),
    ('NAME', '정우연'),
    ('NAME', '한상진'),
    ('NAME', '이하늘'),
    ('NAME', '김지영'),
    ('NAME', '이정하'),
    ('NAME', '박정민'),
    ('NAME', '정다빈'),
    ('NAME', '한상미'),
    ('NAME', '이재영'),
    ('NAME', '김태훈'),
    ('NAME', '이소연'),
    ('NAME', '박민영'),
    ('NAME', '정유진'),
    ('NAME', '한지훈'),
    ('NAME', '이상희'),
    ('NAME', '김상희'),
    ('NAME', '이재원'),
    ('NAME', '박지영'),
    ('NAME', '정민수'),
    ('NAME', '한지우'),
    ('NAME', '이상호'),
    ('NAME', '김민서'),
    ('NAME', '이재민'),
    ('NAME', '박상현'),
    ('NAME', '정하늘'),
    ('NAME', '한상우'),
    ('NAME', '이정훈'),
    ('NAME', '김지훈'),
    ('NAME', '이하영'),
    ('NAME', '박정우'),
    ('NAME', '정민정'),
    ('NAME', '한상철'),
    ('NAME', '이재희'),
    ('NAME', '김유진'),
    ('NAME', '이정수'),
    ('NAME', '박상미'),
    ('NAME', '정재훈'),
    ('NAME', '한지영'),
    ('NAME', '이상철'),
    ('NAME', '김민규'),
    ('NAME', '이재호'),
    ('NAME', '박지수'),
    ('NAME', '정우진'),
    ('NAME', '한상민'),
    ('NAME', '이정민')
;